#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : argcomplete
Version  : 1.5.1
Release  : 17
URL      : https://pypi.python.org/packages/4f/3e/83a0462db52be54427b9d3dca6cab3e6d9d4014f33781bb494e2d6a3a8ef/argcomplete-1.5.1.tar.gz
Source0  : https://pypi.python.org/packages/4f/3e/83a0462db52be54427b9d3dca6cab3e6d9d4014f33781bb494e2d6a3a8ef/argcomplete-1.5.1.tar.gz
Summary  : Bash tab completion for argparse
Group    : Development/Tools
License  : Apache-2.0
Requires: argcomplete-bin
Requires: argcomplete-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
argcomplete - Bash tab completion for argparse
==============================================
*Tab complete all the things!*

%package bin
Summary: bin components for the argcomplete package.
Group: Binaries

%description bin
bin components for the argcomplete package.


%package python
Summary: python components for the argcomplete package.
Group: Default

%description python
python components for the argcomplete package.


%prep
%setup -q -n argcomplete-1.5.1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test --verbose test/test.py || :
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/activate-global-python-argcomplete
/usr/bin/python-argcomplete-check-easy-install-script
/usr/bin/register-python-argcomplete

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
